version: '3.9'

services:
    decidim:
        image: decidim/decidim:latest
        env_file: .env
        working_dir: /app
        volumes:
            - ./db/seeds.rb:/app/db/seeds.rb
        entrypoint: ["/app/entrypoint.sh"]
        container_name: decidim_b3
        networks:
            - external_net
        ports:
            - "${PORT}:3000"

networks:
    external_net:
        external: true
        name: solucion_default
