
version: '3.9'

services:
    pg:
        image: postgres:15
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - pg-data:/var/lib/postgresql/data
        networks:
            - decidim_net

    app:
        image: decidim/decidim:latest
        env_file: ./.env
        working_dir: /app
        volumes:
            - ./flask/instancias/decidim_$a3:/app
            - bundle:/usr/local/bundle
            - node_modules:/app/node_modules
        environment:
            - PORT=3000
            - DATABASE_HOST=pg
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=postgres
            - RAILS_ENV=development
        ports:
            - "$3001:3000"
        networks:
            - decidim_net
        depends_on:
            - pg
        command: bundle exec puma

volumes:
    pg-data: 
    node_modules: 
    bundle: 

networks:
    decidim_net:
